apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    labels:
        component: api
spec:
    replicas: 3
    selector:
        matchLabels:
             component: api
    template:
        metadata: 
            labels:
                component: api
        spec:
            containers:
              -  name: api
                 image: sashakil/final-server
                 ports:
                   -  containerPort: 5000
                 env:
                   - name: REDIS_HOST
                     value: redis-cluster-ip-service
                   - name: REDIS_PORT
                     value: '6379'
                   - name: PGUSER
                     value: sashakil
                   - name: PGHOST
                     value: postgres-cluster-ip-service
                   - name: PGPORT
                     value: '5432'
                   - name: PGDATABASE
                     value: kubernetes
                   - name: PGPASSWORD
                     valueFrom:
                         secretKeyRef:
                               name:  pgpassword
                               key: PGPASSWORD
